version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080

  db:
    image: "hub.roky.work/library/mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
